app = 'hardwarestack'
primary_region = 'arn'

[deploy]
  release_command = "sh -c 'node_modules/.bin/prisma migrate deploy && node_modules/.bin/tsx prisma/seed.ts'"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  PORT = "3000"
  NODE_ENV = "production"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
